<?php
declare(strict_types=1);

namespace M4W\Core;

/**
 * Static configuration (config/config.php). Runtime settings editable from the
 * admin console live in the database, see Settings.
 */
final class Config
{
    private static array $data = [];
    private static bool $installed = false;

    public static function path(): string
    {
        return getenv('M4W_CONFIG') ?: M4W_ROOT . '/config/config.php';
    }

    public static function load(): void
    {
        $defaults = [
            'debug'        => false,
            'timezone'     => 'Europe/Paris',
            'storage_path' => M4W_ROOT . '/storage',
            'db'           => ['driver' => 'sqlite', 'path' => M4W_ROOT . '/storage/data/m4w.sqlite'],
            'app_key'      => '',
            'base_url'     => '',
            'trusted_proxies' => [],
        ];
        $file = self::path();
        if (is_file($file)) {
            $cfg = require $file;
            if (is_array($cfg)) {
                self::$data = array_replace_recursive($defaults, $cfg);
                self::$installed = !empty(self::$data['app_key']);
                return;
            }
        }
        self::$data = $defaults;
    }

    public static function installed(): bool
    {
        return self::$installed;
    }

    public static function get(string $key, mixed $default = null): mixed
    {
        $node = self::$data;
        foreach (explode('.', $key) as $part) {
            if (!is_array($node) || !array_key_exists($part, $node)) {
                return $default;
            }
            $node = $node[$part];
        }
        return $node;
    }

    public static function all(): array
    {
        return self::$data;
    }

    public static function storagePath(string $sub = ''): string
    {
        $base = rtrim((string) self::get('storage_path', M4W_ROOT . '/storage'), '/');
        return $sub === '' ? $base : $base . '/' . ltrim($sub, '/');
    }

    /** Write a fresh config file (installer). */
    public static function write(array $cfg): void
    {
        $php = "<?php\n// Generated by the Make4Web Mail installer on " . date('c') . "\n"
            . "// Keep this file private: it contains the application encryption key.\n"
            . 'return ' . var_export($cfg, true) . ";\n";
        $file = self::path();
        if (!is_dir(dirname($file))) {
            mkdir(dirname($file), 0750, true);
        }
        file_put_contents($file, $php, LOCK_EX);
        @chmod($file, 0640);
        self::load();
    }
}
